### ISSUE TITLE
sensu-plugins organization

### ISSUE THREAD

**Issue by luisdavim** [sensu-plugins/sensu-plugins-chrony#4]
Hi,

would you consider moving this to the github org for community plugins?
The process is still being defined but you can check this here:
https://github.com/sensu-plugins/community/blob/7f217032e9657646fd4264aae7e4d4853768173f/TRANSFERRING_REPOS.md

if you're interested we can also discuss this further on slack:
http://sensucommunityslack.herokuapp.com/

Thanks,
Luis

**Comment by m4ce** [comment]
@luisdavim, I would be happy to. If you could help me out in moving this across, it'd be great. I don't happen to have much time for this right now.

**Comment by majormoses** [comment]
@m4ce I can help facilitate the transfer if you could please follow the instructions and initiate the transfer to me I can transfer it to the org.

**Comment by luisdavim** [comment]
Thanks @majormoses

**Comment by majormoses** [comment]
I have merged the official process into the community repo: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md

**Comment by m4ce** [comment]
@majormoses, I've initiated the transfer.

**Comment by majormoses** [comment]
transfered: https://github.com/sensu-plugins/sensu-plugins-chrony

**Comment by majormoses** [comment]
closing this out and creating issue #5  to track setting up the automated deploys and other random things.

**Comment by luisdavim** [comment]
@m4ce if you have other plugins that you don't have time to maintain please do the same for those and let the community maintain them.

Thanks.
