### ISSUE TITLE
metrics-chrony.rb undefined method

### ISSUE THREAD

**Issue by rideallday** [sensu-plugins/sensu-plugins-chrony#8]
I am getting message after updates on metrics-chrony.rb:

`Check failed to run: undefined method `empty?' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-chrony-1.0.0/bin/metrics-chrony.rb:45:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.0.1/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]`

I see some changes were made about a month ago to a method name, but don't see why that would break.

**Comment by majormoses** [comment]
fixed via #9
